"""
Mythos - Consolidated Project Wisdom
=====================================

Stores high-level architectural wisdom extracted from LoreBook entries.
Represents the "Universal Principles" and "Solved Patterns" of the project.

Author: ARC SAGA Development Team
Date: December 25, 2025
Status: USMA Phase 2 - Instant Intuition
"""

import logging
from datetime import datetime
from typing import Literal
from uuid import uuid4

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


class SolvedPattern(BaseModel):
    """A pattern that has been validated and should be reused."""
    pattern_id: str = Field(default_factory=lambda: str(uuid4()))
    name: str
    description: str
    example: str = ""
    confidence: float = 0.8  # How reliable is this pattern
    usage_count: int = 1
    tags: list[str] = Field(default_factory=list)


class ArchitecturalDebt(BaseModel):
    """Technical debt or anti-pattern that should be avoided."""
    debt_id: str = Field(default_factory=lambda: str(uuid4()))
    name: str
    description: str
    severity: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = "MEDIUM"
    suggested_fix: str = ""


class MythosChapter(BaseModel):
    """
    A consolidated chapter of project wisdom.

    Generated by rolling up 20-50 LoreEntries into universal principles.
    Represents the "narrative arc" of a development phase.
    """
    chapter_id: str = Field(default_factory=lambda: str(uuid4()))
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # Narrative
    title: str  # e.g., "The Parallel Sovereignty Era"
    summary: str  # High-level narrative of what happened

    # Extracted Wisdom
    solved_patterns: list[SolvedPattern] = Field(default_factory=list)
    architectural_debt: list[ArchitecturalDebt] = Field(default_factory=list)
    universal_principles: list[str] = Field(default_factory=list)

    # Provenance
    lore_entry_ids: list[str] = Field(default_factory=list)  # Source entries
    entry_count: int = 0

    # Metadata
    phase: str = ""  # e.g., "Phase 3.0"
    tags: list[str] = Field(default_factory=list)

    def to_context_block(self) -> str:
        """
        Generate a context block suitable for system prompt injection.
        Used by ContextWarden for CAG.
        """
        lines = [
            f"## Mythos: {self.title}",
            f"*Phase: {self.phase}*",
            "",
            self.summary,
            "",
        ]

        if self.universal_principles:
            lines.append("### Universal Principles")
            for principle in self.universal_principles:
                lines.append(f"- {principle}")
            lines.append("")

        if self.solved_patterns:
            lines.append("### Solved Patterns")
            for pattern in self.solved_patterns[:5]:  # Limit for token efficiency
                lines.append(f"- **{pattern.name}**: {pattern.description}")
            lines.append("")

        if self.architectural_debt:
            lines.append("### ⚠️ Avoid (Architectural Debt)")
            for debt in self.architectural_debt[:3]:
                lines.append(f"- [{debt.severity}] {debt.name}: {debt.description}")

        return "\n".join(lines)


class MythosLibrary(BaseModel):
    """
    Collection of all Mythos chapters.
    The project's accumulated wisdom across time.
    """
    chapters: list[MythosChapter] = Field(default_factory=list)
    last_consolidation: datetime | None = None
    total_lore_processed: int = 0

    def get_recent_chapters(self, count: int = 3) -> list[MythosChapter]:
        """Get the N most recent chapters for CAG injection."""
        return sorted(
            self.chapters,
            key=lambda c: c.created_at,
            reverse=True
        )[:count]

    def get_all_principles(self) -> list[str]:
        """Aggregate all universal principles across chapters."""
        principles: list[str] = []
        for chapter in self.chapters:
            principles.extend(chapter.universal_principles)
        return list(set(principles))  # Deduplicate

    def get_all_patterns(self) -> list[SolvedPattern]:
        """Aggregate all solved patterns across chapters."""
        patterns: list[SolvedPattern] = []
        for chapter in self.chapters:
            patterns.extend(chapter.solved_patterns)
        return patterns

    def add_chapter(self, chapter: MythosChapter) -> None:
        """Add a new chapter and update metadata."""
        self.chapters.append(chapter)
        self.last_consolidation = datetime.utcnow()
        self.total_lore_processed += chapter.entry_count
        logger.info(f"Added Mythos chapter: {chapter.title} ({chapter.entry_count} entries)")

    def to_dict(self) -> dict:
        """Serialize for persistence."""
        return self.model_dump(mode='json')

    @classmethod
    def from_dict(cls, data: dict) -> "MythosLibrary":
        """Deserialize from persistence."""
        return cls.model_validate(data)
